-- Hike salary of 150 based on job history and commission pct
DECLARE
  V_COUNT NUMBER(2);
  V_PER NUMBER(2);
BEGIN
  SELECT COUNT(*) INTO V_COUNT
  FROM JOB_HISTORY
  WHERE EMPLOYEE_ID = 150;
  
  IF V_COUNT > 0 THEN
     V_PER := 15;
  ELSE
     SELECT NVL2(COMMISSION_PCT,5,10) INTO V_PER
     FROM EMPLOYEES
     WHERE EMPLOYEE_ID = 150;
  END IF;
  
  UPDATE EMPLOYEES 
   SET SALARY = SALARY + SALARY * V_PER / 100
  WHERE EMPLOYEE_ID = 150;
END;
